import express from 'express';
import multer from 'multer';
import path from 'path';
import { fileURLToPath } from 'url';
import { existsSync, mkdirSync, unlinkSync } from 'fs';
import { authenticate, requireRole } from '../middleware/auth.js';
import UserStore from '../services/UserStore.js';
import AuthService from '../services/AuthService.js';
import { v4 as uuidv4 } from 'uuid';
import { randomUUID } from 'crypto';
import EmailService from '../services/EmailService.js';
import { ActivationTokens, Assessments, RoleLibrary, GeneratedContent, Groups } from '../services/DataStore.js';
import { randomBytes } from 'crypto';
import { getGroups } from '../db/store.js';

function generatePassword() {
  const chars = 'ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';
  let s = '';
  const bytes = randomBytes(8);
  for (let i = 0; i < 8; i++) s += chars[bytes[i] % chars.length];
  return `Skill@${s}`;
}

// ── Balanced question picker from pre-generated bank (NO LLM calls) ───────────
function pickFromBank(bank, target = 10) {
  if (!bank?.length) return [];
  const shuffle = arr => [...arr].sort(() => Math.random() - 0.5);
  const easy   = shuffle(bank.filter(q => q.difficulty === 'easy'));
  const medium = shuffle(bank.filter(q => q.difficulty === 'medium'));
  const hard   = shuffle(bank.filter(q => q.difficulty === 'hard'));
  const n      = Math.min(target, bank.length);
  const eN = Math.round(n * 0.4);
  const mN = Math.round(n * 0.4);
  const hN = n - eN - mN;
  let picked = [...easy.slice(0, eN), ...medium.slice(0, mN), ...hard.slice(0, hN)];
  if (picked.length < n) {
    const used = new Set(picked.map(q => q.id));
    picked = [...picked, ...shuffle(bank).filter(q => !used.has(q.id))].slice(0, n);
  }
  return picked;
}

// Auto-assign a pre-assessment from the Role Library's existing question bank.
// NO API / LLM calls — uses only pre-approved questions stored in DB.
async function autoAssignPreAssessment(user) {
  if (!user.jobRole) return;
  try {
    const companyId = user.companyId || 'default';
    const roleMatch = await RoleLibrary.findByName(user.jobRole, companyId);
    const bank = roleMatch?.questionBank || [];

    if (bank.length < 5) {
      console.warn(`[auto-assessment] Role "${user.jobRole}" has no question bank (${bank.length} q) — skipping`);
      return;
    }

    const questions = pickFromBank(bank, 10);
    const assessmentId = randomUUID();
    const assessment = {
      id: assessmentId,
      title: `Pre-Assessment: ${user.jobRole}`,
      targetUsers: [user.userId],
      employeeAssignments: [{
        userId: user.userId, userName: user.name, userEmail: user.email,
        jobRole: user.jobRole, questions, status: 'assigned',
        assignedAt: new Date().toISOString(), startedAt: null, submittedAt: null,
      }],
      questionCount: questions.length, questionTypes: ['mcq'], duration: 30,
      createdBy: 'system', companyId,
      isAutoGenerated: true, autoTrigger: 'user_onboarding',
      fromRoleId: roleMatch?.id || null,
      createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), isActive: true,
    };

    await Assessments.create(assessment);
    console.log(`[auto-assessment] Assigned to ${user.email} (${user.jobRole}) — ${questions.length} questions from bank`);
  } catch (e) {
    console.error(`[auto-assessment] Failed for ${user.email}:`, e.message);
  }
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const UPLOADS_DIR = path.join(__dirname, '../data/uploads/jd');
const IMPORT_DIR  = path.join(__dirname, '../data/uploads/import');
if (!existsSync(UPLOADS_DIR)) mkdirSync(UPLOADS_DIR, { recursive: true });
if (!existsSync(IMPORT_DIR))  mkdirSync(IMPORT_DIR,  { recursive: true });

const router = express.Router();

// ── Multer setup for import file uploads ─────────────────────────────────────
const importStorage = multer.diskStorage({
  destination: (_req, _file, cb) => cb(null, IMPORT_DIR),
  filename: (_req, file, cb) => {
    cb(null, `import-${Date.now()}-${uuidv4().slice(0, 6)}${path.extname(file.originalname)}`);
  },
});
const importUpload = multer({
  storage: importStorage,
  limits: { fileSize: 10 * 1024 * 1024 }, // 10MB
  fileFilter: (_req, file, cb) => {
    const allowed = ['.csv', '.xls', '.xlsx'];
    const ext = path.extname(file.originalname).toLowerCase();
    cb(null, allowed.includes(ext));
  },
});

// ── Parse import sheet → array of row objects ─────────────────────────────────
async function parseImportFile(filePath) {
  const XLSX = await import('xlsx');
  const wb = XLSX.default.readFile(filePath, { cellDates: true });
  const ws = wb.Sheets[wb.SheetNames[0]];
  const rows = XLSX.default.utils.sheet_to_json(ws, { defval: '' });
  return rows;
}

// Normalise column name variants to canonical keys
const COL_MAP = {
  name: 'name', full_name: 'name', fullname: 'name', 'full name': 'name',
  email: 'email', email_address: 'email', 'email address': 'email',
  role: 'role', user_role: 'role', system_role: 'role', 'system role': 'role', 'system_role': 'role',
  employee_id: 'employeeId', 'employee id': 'employeeId', employeeid: 'employeeId', emp_id: 'employeeId',
  job_role: 'jobRole', jobrole: 'jobRole', 'job role': 'jobRole', position: 'jobRole', title: 'jobRole',
  department: 'department', dept: 'department',
  job_description: 'jobDescription', 'job description': 'jobDescription', jd: 'jobDescription',
  company_name: 'companyName', 'company name': 'companyName', company: 'companyName',
  password: 'password', temp_password: 'password', 'temp password': 'password',
  phone: 'phone', phone_number: 'phone', 'phone number': 'phone',
  status: 'status',
  manager_email: 'managerEmail', 'manager email': 'managerEmail',
};

function normaliseRow(raw) {
  const out = {};
  for (const [k, v] of Object.entries(raw)) {
    const canon = COL_MAP[k.toLowerCase().trim()];
    if (canon) out[canon] = String(v ?? '').trim();
  }
  return out;
}

// ── Multer setup for JD file uploads ─────────────────────────────────────────
const jdStorage = multer.diskStorage({
  destination: (_req, _file, cb) => cb(null, UPLOADS_DIR),
  filename: (_req, file, cb) => {
    const unique = `${Date.now()}-${uuidv4().slice(0, 8)}${path.extname(file.originalname)}`;
    cb(null, unique);
  },
});
const jdUpload = multer({
  storage: jdStorage,
  limits: { fileSize: 50 * 1024 * 1024 }, // 50MB
  fileFilter: (_req, file, cb) => {
    const allowed = ['.pdf', '.doc', '.docx', '.txt', '.rtf', '.odt', '.png', '.jpg', '.jpeg'];
    const ext = path.extname(file.originalname).toLowerCase();
    cb(null, allowed.includes(ext));
  },
});

// ── Sanitize user for response (include all profile fields) ───────────────────
function sanitizeUser(user) {
  return {
    userId: user.userId || user.id,
    email: user.email,
    name: user.name,
    role: user.role,
    emailVerified: user.emailVerified,
    createdAt: user.createdAt,
    updatedAt: user.updatedAt,
    lastLogin: user.lastLogin,
    managerId: user.managerId || null,
    learningUUID: user.learningUUID || null,
    // Extended profile
    jobRole: user.jobRole || '',
    department: user.department || '',
    jobDescription: user.jobDescription || '',
    jobDescriptionFile: user.jobDescriptionFile || null,
    onboardingComplete: user.onboardingComplete || false,
    companyName: user.companyName || '',
    employeeId: user.employeeId || '',
    phone: user.phone || '',
    status: user.status || 'active',
    jdSkills: user.jdSkills || [],
    jdSourceUrl: user.jdSourceUrl || '',
    jdSourceType: user.jdSourceType || 'text',
    accesses: user.accesses || [],
  };
}

/**
 * GET /api/users/role-counts
 * Returns count per unique jobRole for employees in the same company (admin/manager)
 */
router.get('/role-counts', authenticate, requireRole('admin', 'manager'), async (req, res) => {
  try {
    const companyId = req.user.companyId || 'default';
    const allUsers = await UserStore.getAllUsers({ role: 'employee' });
    const companyEmployees = allUsers.filter(u => (u.companyId || 'default') === companyId);

    const counts = {};
    for (const u of companyEmployees) {
      const jobRole = (u.jobRole || '').trim();
      if (!jobRole) continue;
      counts[jobRole] = (counts[jobRole] || 0) + 1;
    }

    res.json({ success: true, data: counts, error: null });
  } catch (error) {
    console.error('[User Routes] Role counts error:', error.message);
    res.status(500).json({ success: false, data: null, error: { code: 'USER_ERROR', message: 'Failed to get role counts' } });
  }
});

/**
 * GET /api/users
 * Get all users (admin/manager)
 */
router.get('/', authenticate, async (req, res) => {
  try {
    const isAdmin = req.user.role === 'admin';
    const isManager = req.user.role === 'manager';
    if (!isAdmin && !isManager) {
      return res.status(403).json({ success: false, data: null, error: { code: 'AUTH_FORBIDDEN', message: 'Access denied' } });
    }

    const { role, emailVerified } = req.query;
    const filters = {};
    if (role) filters.role = role;
    if (emailVerified !== undefined) filters.emailVerified = emailVerified === 'true';
    if (isManager && !filters.role) filters.role = 'employee';

    const allUsers = await UserStore.getAllUsers(filters);
    // Company isolation: both admin and manager only see their own company's users
    const myCompany = req.user.companyId || 'default';
    let users = (isAdmin || isManager)
      ? allUsers.filter(u => (u.companyId || 'default') === myCompany)
      : allUsers;

    // Manager group filtering: restrict to employees in manager's assigned groups
    if (isManager) {
      try {
        const allGroups = await getGroups();
        const managerGroups = allGroups.filter(g =>
          g.managerId === req.user.userId &&
          (g.companyId || 'default') === (req.user.companyId || 'default')
        );
        if (managerGroups.length > 0) {
          // employeeIds is stored directly on the group object (not in group_memberships table)
          const memberUserIds = new Set(managerGroups.flatMap(g => g.employeeIds || []));
          if (memberUserIds.size > 0) {
            users = users.filter(u => memberUserIds.has(u.userId));
          }
          // If groups exist but have no members yet, return empty list (not all employees)
        } else {
          // Manager has no groups assigned — show nothing
          users = [];
        }
      } catch (groupErr) {
        console.warn('[User Routes] Group filtering failed, returning company employees:', groupErr.message);
      }
    }

    const sanitizedUsers = users.map(sanitizeUser);

    res.json({ success: true, data: { users: sanitizedUsers, count: sanitizedUsers.length }, error: null });
  } catch (error) {
    console.error('[User Routes] Get all users error:', error.message);
    res.status(500).json({ success: false, data: null, error: { code: 'USER_ERROR', message: 'Failed to get users' } });
  }
});

/**
 * POST /api/users
 * Admin/Manager creates a new user directly (bypasses email signup)
 */
router.post('/', authenticate, requireRole('admin', 'manager'), async (req, res) => {
  try {
    const { email, name, role, jobRole, department, jobDescription, companyName, password } = req.body;

    if (!email || !name) {
      return res.status(400).json({ success: false, data: null, error: { code: 'USER_INVALID_INPUT', message: 'Email and name are required' } });
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return res.status(400).json({ success: false, data: null, error: { code: 'USER_INVALID_EMAIL', message: 'Invalid email format' } });
    }

    // Prevent duplicate
    const existing = await UserStore.getUserByEmail(email);
    if (existing) {
      return res.status(409).json({ success: false, data: null, error: { code: 'USER_EMAIL_EXISTS', message: 'Email already registered' } });
    }

    // Managers can only create employees
    const assignedRole = (req.user.role === 'manager') ? 'employee' : (role || 'employee');
    // Generate a placeholder hash — user will set real password via activation link
    const placeholderHash = await AuthService.hashPassword(uuidv4());

    const user = await UserStore.createUser({
      email,
      passwordHash: placeholderHash,
      name: name.trim(),
      role: assignedRole,
      emailVerified: false,
      onboardingComplete: false,
      jobRole: jobRole || '',
      department: department || '',
      jobDescription: jobDescription || '',
      companyName: companyName || '',
      companyId: req.user.companyId || 'default',
    });

    await UserStore.logAuthEvent('user_created_by_admin', user.userId, {
      createdBy: req.user.userId,
      createdByRole: req.user.role,
      ipAddress: req.ip,
    });

    // Create activation token and attempt email — 25s timeout to survive SMTP retries
    let emailSent = false;
    let emailError = null;
    let activationUrl = null;
    try {
      const tokenId = uuidv4();
      const expiresAt = new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString();
      await ActivationTokens.create({ id: tokenId, userId: user.userId, email: user.email, expiresAt, used: false });
      const frontendUrl = process.env.FRONTEND_URL || 'https://skillforge-swart-mu.vercel.app';
      activationUrl = `${frontendUrl}/auth/activate?token=${tokenId}`;
      const timeout = new Promise(resolve => setTimeout(() => resolve({ success: false, error: 'timeout' }), 25000));
      const result = await Promise.race([
        EmailService.sendInvitationEmail(user.email, {
          name: user.name,
          role: user.role,
          companyName: user.companyName || req.user.companyName || 'SkillForge AI',
          activationUrl,
          fromEmail: req.user.email,
          fromName: req.user.name || user.companyName || 'SkillForge AI',
        }),
        timeout,
      ]);
      emailSent = result?.success === true;
      if (!emailSent) {
        emailError = result?.error || 'Unknown error';
        console.warn(`[users] Invitation email to ${user.email} failed: ${emailError}`);
      }
    } catch (emailErr) {
      emailError = emailErr.message;
      console.warn('[users] Invitation email failed:', emailErr.message);
    }

    // Auto-assign role-specific pre-assessment (non-blocking)
    if (user.jobRole) setImmediate(() => autoAssignPreAssessment(user));

    res.status(201).json({
      success: true,
      data: {
        ...sanitizeUser(user),
        emailSent,
        emailError,
        activationUrl,
      },
      error: null,
    });
  } catch (error) {
    console.error('[User Routes] Create user error:', error.message);
    res.status(500).json({ success: false, data: null, error: { code: 'USER_ERROR', message: 'Failed to create user' } });
  }
});

/**
 * GET /api/users/:userId
 * Get user by ID (self, admin, or manager of this user)
 */
router.get('/:userId', authenticate, async (req, res) => {
  try {
    const { userId } = req.params;
    const isSelf = req.user.userId === userId;
    const isAdmin = req.user.role === 'admin';
    const isManager = req.user.role === 'manager';

    if (!isSelf && !isAdmin && !isManager) {
      return res.status(403).json({ success: false, data: null, error: { code: 'AUTH_FORBIDDEN', message: 'Access denied' } });
    }

    const user = await UserStore.getUserById(userId);
    if (!user) {
      return res.status(404).json({ success: false, data: null, error: { code: 'USER_NOT_FOUND', message: 'User not found' } });
    }

    res.json({ success: true, data: sanitizeUser(user), error: null });
  } catch (error) {
    console.error('[User Routes] Get user error:', error.message);
    res.status(500).json({ success: false, data: null, error: { code: 'USER_ERROR', message: 'Failed to get user' } });
  }
});

/**
 * PUT /api/users/:userId
 * Update user profile — self can update own info; admin/manager can update all fields
 */
router.put('/:userId', authenticate, async (req, res) => {
  try {
    const { userId } = req.params;
    const isSelf = req.user.userId === userId;
    const isAdmin = req.user.role === 'admin';
    const isManager = req.user.role === 'manager';

    if (!isSelf && !isAdmin && !isManager) {
      return res.status(403).json({ success: false, data: null, error: { code: 'AUTH_FORBIDDEN', message: 'Cannot update this user' } });
    }

    const user = await UserStore.getUserById(userId);
    if (!user) {
      return res.status(404).json({ success: false, data: null, error: { code: 'USER_NOT_FOUND', message: 'User not found' } });
    }

    const { name, email, role, status, jobRole, department, jobDescription, companyName, onboardingComplete } = req.body;
    const updates = {};

    // Name — anyone can update own name; admin/manager can update any
    if (name !== undefined) {
      if (!name.trim()) return res.status(400).json({ success: false, data: null, error: { code: 'USER_INVALID_NAME', message: 'Name cannot be empty' } });
      updates.name = name.trim();
    }

    // Email — self or admin only
    if (email !== undefined && email !== user.email) {
      if (!isSelf && !isAdmin) return res.status(403).json({ success: false, data: null, error: { code: 'AUTH_FORBIDDEN', message: 'Only admin can change email' } });
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(email)) return res.status(400).json({ success: false, data: null, error: { code: 'USER_INVALID_EMAIL', message: 'Invalid email format' } });
      const existingUser = await UserStore.getUserByEmail(email);
      if (existingUser && existingUser.userId !== userId) {
        return res.status(409).json({ success: false, data: null, error: { code: 'USER_EMAIL_EXISTS', message: 'Email already in use' } });
      }
      updates.email = email;
    }

    // Role — admin only
    if (role !== undefined && isAdmin) {
      const validRoles = ['admin', 'manager', 'employee'];
      if (validRoles.includes(role)) updates.role = role;
    }

    // Status — admin or manager only
    if (status !== undefined && (isAdmin || isManager)) {
      const validStatuses = ['active', 'inactive', 'blocked'];
      if (validStatuses.includes(status)) updates.status = status;
    }

    // Extended profile — admin or manager can set; self can set own
    if (jobRole !== undefined) updates.jobRole = jobRole;
    if (department !== undefined) updates.department = department;
    if (jobDescription !== undefined) updates.jobDescription = jobDescription; // no char limit
    if (companyName !== undefined) updates.companyName = companyName;
    if (onboardingComplete !== undefined && (isAdmin || isManager || isSelf)) {
      updates.onboardingComplete = !!onboardingComplete;
    }

    updates.updatedAt = new Date().toISOString();

    if (Object.keys(updates).length === 1 && updates.updatedAt) {
      return res.status(400).json({ success: false, data: null, error: { code: 'USER_NO_UPDATES', message: 'No valid updates provided' } });
    }

    const updatedUser = await UserStore.updateUser(userId, updates);
    await UserStore.logAuthEvent('profile_updated', userId, { updates: Object.keys(updates), updatedBy: req.user.userId, ipAddress: req.ip });

    // Priority 6: Role changed → auto-assign role-tagged modules (non-blocking)
    if (updates.jobRole && updates.jobRole !== user.jobRole) {
      (async () => {
        try {
          const { RoleLibrary } = await import('../services/DataStore.js');
          const db = await import('../db/store.js');
          const roleMatch = await RoleLibrary.findByName(updates.jobRole, updatedUser.companyId || 'default');
          if (!roleMatch) return;
          const allModules = await db.getModules();
          const roleModules = allModules.filter(m =>
            (m.targetRoles || []).some(r => r.toLowerCase() === updates.jobRole.toLowerCase())
          );
          for (const mod of roleModules) {
            try {
              await db.createAssignment({
                employeeId: userId, assignableId: mod.id, assignable_type: 'module',
                type: 'module', title: mod.title, module_name: mod.title,
                status: 'assigned', progress: 0,
                companyId: updatedUser.companyId || 'default',
                assignedBy: req.user.userId, assignedByRole: req.user.role,
                autoAssigned: true, autoAssignedReason: `Role: ${updates.jobRole}`,
              });
            } catch {}
          }
        } catch (e) { console.warn('[auto-assign modules] role change trigger:', e.message); }
      })();
    }

    res.json({ success: true, data: sanitizeUser(updatedUser), error: null });
  } catch (error) {
    console.error('[User Routes] Update user error:', error.message);
    res.status(500).json({ success: false, data: null, error: { code: 'USER_ERROR', message: 'Failed to update user' } });
  }
});

/**
 * POST /api/users/:userId/jd-upload
 * Upload JD file (PDF, DOCX, TXT, etc.) — admin/manager or self
 * Replaces any previous JD for this user.
 * Extracts full text + skills from file, stores in DB, then deletes the file.
 */
router.post('/:userId/jd-upload', authenticate, jdUpload.single('jd'), async (req, res) => {
  const uploadedPath = req.file?.path;
  try {
    const { userId } = req.params;
    const isSelf = req.user.userId === userId;
    const isAdmin = req.user.role === 'admin';
    const isManager = req.user.role === 'manager';

    if (!isSelf && !isAdmin && !isManager) {
      return res.status(403).json({ success: false, data: null, error: { code: 'AUTH_FORBIDDEN', message: 'Access denied' } });
    }

    const user = await UserStore.getUserById(userId);
    if (!user) {
      return res.status(404).json({ success: false, data: null, error: { code: 'USER_NOT_FOUND', message: 'User not found' } });
    }

    if (!req.file) {
      return res.status(400).json({ success: false, data: null, error: { code: 'NO_FILE', message: 'No file uploaded' } });
    }

    // Extract full text from the uploaded file — no character limit
    const { parseJDFile, extractSkillsFromJDText } = await import('../utils/parseJDFile.js');
    const extractedText = await parseJDFile(req.file.path, req.file.originalname);

    if (!extractedText || extractedText.length < 20) {
      return res.status(422).json({ success: false, data: null, error: { code: 'JD_EMPTY', message: 'Could not extract text from this file. Try PDF, DOCX, or TXT.' } });
    }

    const skills = extractSkillsFromJDText(extractedText);

    // Persist extracted text + skills; keep metadata (name/size) but clear file path
    const updatedUser = await UserStore.updateUser(userId, {
      jobDescription: extractedText,          // canonical text used everywhere
      jobDescriptionFile: {                   // metadata only — path cleared
        name: req.file.originalname,
        size: req.file.size,
        type: req.file.mimetype,
        uploadedAt: new Date().toISOString(),
        path: null,                           // file is deleted below
      },
      jdSkills: skills,
      jdSourceType: 'file',
      jdSourceUrl: '',
      updatedAt: new Date().toISOString(),
    });

    await UserStore.logAuthEvent('jd_uploaded', userId, {
      uploadedBy: req.user.userId,
      fileName: req.file.originalname,
      extractedChars: extractedText.length,
      skillsFound: skills.length,
      ipAddress: req.ip,
    });

    res.json({
      success: true,
      data: {
        extractedChars: extractedText.length,
        skillsFound: skills,
        jdSourceType: 'file',
        user: sanitizeUser(updatedUser),
      },
      error: null,
    });
  } catch (error) {
    console.error('[User Routes] JD upload error:', error.message);
    res.status(500).json({ success: false, data: null, error: { code: 'UPLOAD_ERROR', message: 'File upload failed: ' + error.message } });
  } finally {
    // Always delete the uploaded file — text is now stored in DB
    if (uploadedPath) { try { unlinkSync(uploadedPath); } catch {} }
  }
});

/**
 * POST /api/users/:userId/jd-url
 * Fetch JD from a public URL (Google Drive, OneDrive, Dropbox, direct link).
 * Extracts text + skills, stores in DB. No file is kept.
 */
router.post('/:userId/jd-url', authenticate, async (req, res) => {
  try {
    const { userId } = req.params;
    const isSelf = req.user.userId === userId;
    const isAdmin = req.user.role === 'admin';
    const isManager = req.user.role === 'manager';

    if (!isSelf && !isAdmin && !isManager) {
      return res.status(403).json({ success: false, data: null, error: { code: 'AUTH_FORBIDDEN', message: 'Access denied' } });
    }

    const user = await UserStore.getUserById(userId);
    if (!user) {
      return res.status(404).json({ success: false, data: null, error: { code: 'USER_NOT_FOUND', message: 'User not found' } });
    }

    const { url } = req.body;
    if (!url || !url.trim()) {
      return res.status(400).json({ success: false, data: null, error: { code: 'NO_URL', message: 'URL is required' } });
    }

    // Basic URL validation
    let parsed;
    try { parsed = new URL(url.trim()); } catch {
      return res.status(400).json({ success: false, data: null, error: { code: 'INVALID_URL', message: 'Invalid URL format' } });
    }
    if (!['http:', 'https:'].includes(parsed.protocol)) {
      return res.status(400).json({ success: false, data: null, error: { code: 'INVALID_URL', message: 'Only http/https URLs are supported' } });
    }

    const { fetchJDFromUrl } = await import('../utils/fetchJDUrl.js');
    const { extractSkillsFromJDText } = await import('../utils/parseJDFile.js');

    const { text: extractedText, source } = await fetchJDFromUrl(url.trim());
    const skills = extractSkillsFromJDText(extractedText);

    const updatedUser = await UserStore.updateUser(userId, {
      jobDescription: extractedText,
      jobDescriptionFile: null,               // no file — URL source
      jdSkills: skills,
      jdSourceUrl: url.trim(),
      jdSourceType: 'url',
      updatedAt: new Date().toISOString(),
    });

    await UserStore.logAuthEvent('jd_url_saved', userId, {
      savedBy: req.user.userId,
      sourceUrl: url.trim(),
      source,
      extractedChars: extractedText.length,
      skillsFound: skills.length,
      ipAddress: req.ip,
    });

    res.json({
      success: true,
      data: {
        extractedChars: extractedText.length,
        skillsFound: skills,
        jdSourceType: 'url',
        jdSourceUrl: url.trim(),
        user: sanitizeUser(updatedUser),
      },
      error: null,
    });
  } catch (error) {
    console.error('[User Routes] JD URL error:', error.message);
    res.status(422).json({ success: false, data: null, error: { code: 'JD_URL_ERROR', message: error.message } });
  }
});

/**
 * GET /api/users/:userId/jd
 * Get the JD text + file info for a user (self, admin, or manager)
 */
router.get('/:userId/jd', authenticate, async (req, res) => {
  try {
    const { userId } = req.params;
    const isSelf = req.user.userId === userId;
    const isAdmin = req.user.role === 'admin';
    const isManager = req.user.role === 'manager';

    if (!isSelf && !isAdmin && !isManager) {
      return res.status(403).json({ success: false, data: null, error: { code: 'AUTH_FORBIDDEN', message: 'Access denied' } });
    }

    const user = await UserStore.getUserById(userId);
    if (!user) {
      return res.status(404).json({ success: false, data: null, error: { code: 'USER_NOT_FOUND', message: 'User not found' } });
    }

    res.json({
      success: true,
      data: {
        jobRole: user.jobRole || '',
        jobDescription: user.jobDescription || '',
        jobDescriptionFile: user.jobDescriptionFile || null,
        hasJD: !!(user.jobDescription || user.jobDescriptionFile),
      },
      error: null,
    });
  } catch (error) {
    console.error('[User Routes] Get JD error:', error.message);
    res.status(500).json({ success: false, data: null, error: { code: 'USER_ERROR', message: 'Failed to get JD' } });
  }
});

/**
 * POST /api/users/:userId/onboarding
 * Complete onboarding step 2 for employee self-signup
 * Accepts: name, jobRole, department, companyName
 */
router.post('/:userId/onboarding', authenticate, async (req, res) => {
  try {
    const { userId } = req.params;
    if (req.user.userId !== userId) {
      return res.status(403).json({ success: false, data: null, error: { code: 'AUTH_FORBIDDEN', message: 'Can only complete own onboarding' } });
    }

    const user = await UserStore.getUserById(userId);
    if (!user) {
      return res.status(404).json({ success: false, data: null, error: { code: 'USER_NOT_FOUND', message: 'User not found' } });
    }

    if (user.onboardingComplete) {
      return res.json({ success: true, data: sanitizeUser(user), error: null }); // idempotent
    }

    const { name, jobRole, department, companyName } = req.body;
    if (!name || !jobRole) {
      return res.status(400).json({ success: false, data: null, error: { code: 'ONBOARDING_INVALID', message: 'Name and job role are required' } });
    }

    const updatedUser = await UserStore.updateUser(userId, {
      name: name.trim(),
      jobRole: jobRole.trim(),
      department: (department || '').trim(),
      companyName: (companyName || '').trim(),
      onboardingComplete: true,
      updatedAt: new Date().toISOString(),
    });

    res.json({ success: true, data: sanitizeUser(updatedUser), error: null });
  } catch (error) {
    console.error('[User Routes] Onboarding error:', error.message);
    res.status(500).json({ success: false, data: null, error: { code: 'ONBOARDING_ERROR', message: 'Failed to complete onboarding' } });
  }
});

/**
 * DELETE /api/users/:userId
 * Delete user (admin only)
 */
router.delete('/:userId', authenticate, requireRole('admin'), async (req, res) => {
  try {
    const { userId } = req.params;
    if (req.user.userId === userId) {
      return res.status(400).json({ success: false, data: null, error: { code: 'USER_CANNOT_DELETE_SELF', message: 'You cannot delete your own account' } });
    }

    const user = await UserStore.getUserById(userId);
    if (!user) {
      return res.status(404).json({ success: false, data: null, error: { code: 'USER_NOT_FOUND', message: 'User not found' } });
    }
    // Company isolation: admin can only delete users in their own company
    if (req.user.role === 'admin' && req.user.companyId !== 'default' && (user.companyId || 'default') !== req.user.companyId) {
      return res.status(403).json({ success: false, data: null, error: { code: 'AUTH_FORBIDDEN', message: 'Cannot delete users from other companies' } });
    }

    await UserStore.deleteUser(userId);
    await UserStore.logAuthEvent('user_deleted', userId, { deletedBy: req.user.userId, deletedUser: { email: user.email, role: user.role }, ipAddress: req.ip });

    res.json({ success: true, data: { message: 'User deleted successfully' }, error: null });
  } catch (error) {
    console.error('[User Routes] Delete user error:', error.message);
    res.status(500).json({ success: false, data: null, error: { code: 'USER_ERROR', message: 'Failed to delete user' } });
  }
});

/**
 * POST /api/users/:userId/resend-invite
 * Resend activation email to a user (admin/manager only)
 */
router.post('/:userId/resend-invite', authenticate, requireRole('admin', 'manager'), async (req, res) => {
  try {
    const user = await UserStore.getUserById(req.params.userId);
    if (!user) return res.status(404).json({ success: false, error: 'User not found' });

    const tokenId = uuidv4();
    const expiresAt = new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString();
    await ActivationTokens.create({ id: tokenId, userId: user.userId, email: user.email, expiresAt, used: false });
    const frontendUrl = process.env.FRONTEND_URL || 'https://skillforge-swart-mu.vercel.app';
    const activationUrl = `${frontendUrl}/auth/activate?token=${tokenId}`;

    const timeout = new Promise(resolve => setTimeout(() => resolve({ success: false, error: 'timeout' }), 25000));
    const result = await Promise.race([
      EmailService.sendInvitationEmail(user.email, {
        name: user.name,
        role: user.role,
        companyName: user.companyName || 'SkillForge AI',
        activationUrl,
        fromEmail: req.user.email,
        fromName: req.user.name || 'SkillForge AI',
      }),
      timeout,
    ]);

    const emailSent = result?.success === true;
    res.json({ success: true, data: { emailSent, emailError: emailSent ? null : result?.error, activationUrl } });
  } catch (e) {
    console.error('[resend-invite]', e.message);
    res.status(500).json({ success: false, error: e.message });
  }
});

/**
 * PUT /api/users/:userId/role
 * Update user role (admin only)
 */
router.put('/:userId/role', authenticate, requireRole('admin'), async (req, res) => {
  try {
    const { userId } = req.params;
    const { role } = req.body;
    const validRoles = ['admin', 'manager', 'employee', 'trainer', 'leadership'];

    if (!role || !validRoles.includes(role)) {
      return res.status(400).json({ success: false, data: null, error: { code: 'USER_INVALID_ROLE', message: `Role must be one of: ${validRoles.join(', ')}` } });
    }

    const user = await UserStore.getUserById(userId);
    if (!user) {
      return res.status(404).json({ success: false, data: null, error: { code: 'USER_NOT_FOUND', message: 'User not found' } });
    }

    const oldRole = user.role;
    const updatedUser = await UserStore.updateUserRole(userId, role);
    await UserStore.logAuthEvent('role_changed', userId, { changedBy: req.user.userId, oldRole, newRole: role, ipAddress: req.ip });

    res.json({ success: true, data: sanitizeUser(updatedUser), error: null });
  } catch (error) {
    console.error('[User Routes] Update role error:', error.message);
    res.status(500).json({ success: false, data: null, error: { code: 'USER_ERROR', message: 'Failed to update role' } });
  }
});

/**
 * PUT /api/users/:userId/accesses
 * Grant/revoke additional platform accesses (admin only).
 * Body: { accesses: ['manager', 'trainer'] }
 */
router.put('/:userId/accesses', authenticate, requireRole('admin'), async (req, res) => {
  try {
    const { userId } = req.params;
    const { accesses } = req.body;
    const validAccesses = ['admin', 'manager', 'trainer'];

    if (!Array.isArray(accesses)) {
      return res.status(400).json({ success: false, data: null, error: 'accesses must be an array' });
    }
    const filtered = accesses.filter(a => validAccesses.includes(a));

    const user = await UserStore.getUserById(userId);
    if (!user) return res.status(404).json({ success: false, data: null, error: 'User not found' });

    // Admins in the same company only
    const myCompany = req.user.companyId || 'default';
    if ((user.companyId || 'default') !== myCompany) {
      return res.status(403).json({ success: false, data: null, error: 'Cannot manage users from another company' });
    }

    const updatedUser = await UserStore.updateUser(userId, { accesses: filtered });
    await UserStore.logAuthEvent('accesses_changed', userId, { changedBy: req.user.userId, accesses: filtered, ipAddress: req.ip });

    res.json({ success: true, data: sanitizeUser(updatedUser), error: null });
  } catch (e) {
    console.error('[User Routes] Update accesses error:', e.message);
    res.status(500).json({ success: false, data: null, error: e.message });
  }
});

/**
 * GET /api/users/:userId/assignments
 * Get user's assignments
 */
router.get('/:userId/assignments', authenticate, async (req, res) => {
  try {
    const { userId } = req.params;
    const isSelf = req.user.userId === userId;
    const isAdmin = req.user.role === 'admin';
    const isManager = req.user.role === 'manager';

    if (!isSelf && !isAdmin && !isManager) {
      const managers = await UserStore.getEmployeeManagers(userId);
      const isThisManager = managers.some(m => m.userId === req.user.userId);
      if (!isThisManager) return res.status(403).json({ success: false, data: null, error: { code: 'AUTH_FORBIDDEN', message: 'Access denied' } });
    }

    const assignments = await UserStore.getAssignments({ user_id: userId });
    res.json({ success: true, data: { assignments, count: assignments.length }, error: null });
  } catch (error) {
    console.error('[User Routes] Get assignments error:', error.message);
    res.status(500).json({ success: false, data: null, error: { code: 'USER_ERROR', message: 'Failed to get assignments' } });
  }
});

/**
 * GET /api/users/:userId/jd-file
 * Download the uploaded JD file for a user
 */
router.get('/:userId/jd-file', authenticate, async (req, res) => {
  try {
    const { userId } = req.params;
    const isSelf = req.user.userId === userId;
    const isAdmin = req.user.role === 'admin';
    const isManager = req.user.role === 'manager';
    if (!isSelf && !isAdmin && !isManager) {
      return res.status(403).json({ success: false, error: 'Access denied' });
    }

    const user = await UserStore.getUserById(userId);
    if (!user?.jobDescriptionFile) {
      return res.status(404).json({ success: false, error: 'No JD file uploaded' });
    }

    const filePath = user.jobDescriptionFile.path || user.jobDescriptionFile.storagePath;
    if (!filePath) return res.status(404).json({ success: false, error: 'File path not found' });

    if (!existsSync(filePath)) {
      return res.status(404).json({ success: false, error: 'File not found on disk' });
    }

    res.download(filePath, user.jobDescriptionFile.name || 'jd-file', (err) => {
      if (err && !res.headersSent) {
        res.status(500).json({ success: false, error: 'Download failed' });
      }
    });
  } catch (error) {
    console.error('[User Routes] JD file download error:', error.message);
    if (!res.headersSent) res.status(500).json({ success: false, error: 'Download failed' });
  }
});

/**
 * POST /api/users/bulk-import/preview
 * Parse an import file and return preview rows with validation — no DB writes.
 */
router.post('/bulk-import/preview', authenticate, requireRole('admin', 'manager'),
  importUpload.single('file'), async (req, res) => {
  const filePath = req.file?.path;
  try {
    if (!filePath) {
      return res.status(400).json({ success: false, error: 'No file uploaded. Supported: CSV, XLS, XLSX' });
    }
    const rawRows = await parseImportFile(filePath);
    if (!rawRows.length) {
      return res.status(400).json({ success: false, error: 'File is empty or has no data rows' });
    }

    const allUsers = await UserStore.getAllUsers({});
    const existingEmailMap = Object.fromEntries(allUsers.map(u => [u.email?.toLowerCase(), u]));
    const existingEmails = new Set(Object.keys(existingEmailMap));
    const existingEmpIds = new Set(allUsers.map(u => u.employeeId).filter(Boolean));
    const seenInBatch = new Set();

    const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    const preview = rawRows.map((raw, idx) => {
      const row = normaliseRow(raw);
      const errors = [];

      const isExisting = row.email && existingEmails.has(row.email.toLowerCase());

      if (!row.name) errors.push('name required');
      if (!row.email) errors.push('email required');
      else if (!EMAIL_RE.test(row.email)) errors.push('invalid email format');
      else if (seenInBatch.has(row.email.toLowerCase())) errors.push('duplicate email in file');
      else seenInBatch.add(row.email.toLowerCase());

      if (row.employeeId && existingEmpIds.has(row.employeeId) && !isExisting) errors.push('employee ID already exists');
      if (row.role && !['employee', 'manager', 'admin'].includes(row.role.toLowerCase())) {
        errors.push(`invalid role "${row.role}" — use employee/manager/admin`);
      }

      return {
        rowNum: idx + 2, // +2 because row 1 = header
        ...row,
        role: row.role?.toLowerCase() || 'employee',
        status: errors.length ? 'error' : (isExisting ? 'update' : 'valid'),
        errors,
        _isUpdate: isExisting,
        _existingUserId: isExisting ? existingEmailMap[row.email.toLowerCase()]?.userId : undefined,
      };
    });

    const valid   = preview.filter(r => r.status === 'valid').length;
    const updates = preview.filter(r => r.status === 'update').length;
    const invalid = preview.filter(r => r.status === 'error').length;
    res.json({ success: true, data: { preview, summary: { total: preview.length, valid, updates, invalid } } });
  } catch (e) {
    console.error('[bulk-import/preview]', e);
    res.status(500).json({ success: false, error: e.message });
  } finally {
    if (filePath) { try { unlinkSync(filePath); } catch {} }
  }
});

/**
 * POST /api/users/bulk-import
 * Accept validated rows (JSON array) and create users in DB.
 */
router.post('/bulk-import', authenticate, requireRole('admin', 'manager'), async (req, res) => {
  try {
    const { rows } = req.body; // array of normalised row objects from preview
    if (!Array.isArray(rows) || !rows.length) {
      return res.status(400).json({ success: false, error: 'rows array required' });
    }

    const companyId  = req.user.companyId || 'default';
    const allUsers   = await UserStore.getAllUsers({});
    const existingEmails = new Set(allUsers.map(u => u.email?.toLowerCase()));

    const created = [], updated = [], skipped = [], failed = [];

    for (const row of rows) {
      if (!row.email || !row.name) { skipped.push({ row, reason: 'Missing name or email' }); continue; }

      const existingUser = allUsers.find(u => u.email?.toLowerCase() === row.email.toLowerCase());

      if (existingUser) {
        // UPDATE path - only update non-empty fields
        try {
          const updateFields = {};
          if (row.name) updateFields.name = row.name.trim();
          if (row.jobRole) updateFields.jobRole = row.jobRole;
          if (row.department) updateFields.department = row.department;
          if (row.jobDescription) updateFields.jobDescription = row.jobDescription;
          if (row.phone) updateFields.phone = row.phone;
          if (row.employeeId) updateFields.employeeId = row.employeeId;
          if (row.status && ['active','inactive','blocked'].includes(row.status)) updateFields.status = row.status;
          // role update only if admin
          if (row.role && req.user.role === 'admin') {
            const r = row.role.toLowerCase();
            if (['employee','manager','admin'].includes(r)) updateFields.role = r;
          }
          if (Object.keys(updateFields).length > 0) {
            await UserStore.updateUser(existingUser.userId || existingUser.id, updateFields);
          }
          updated.push({ userId: existingUser.userId || existingUser.id, email: existingUser.email, name: existingUser.name, updated: Object.keys(updateFields) });
          continue;
        } catch (e) {
          failed.push({ row, reason: e.message });
          continue;
        }
      }

      try {
        const ALLOWED_IMPORT_ROLES = ['employee', 'manager', 'trainer', 'leadership'];
        const requestedRole = (row.role || 'employee').toLowerCase();
        const assignedRole = req.user.role === 'manager'
          ? (['employee', 'trainer'].includes(requestedRole) ? requestedRole : 'employee')
          : (ALLOWED_IMPORT_ROLES.includes(requestedRole) ? requestedRole : 'employee');
        // Generate a real unique password — admin gets it in the credential Excel
        const tempPassword = generatePassword();
        const passwordHash = await AuthService.hashPassword(tempPassword);

        const user = await UserStore.createUser({
          email: row.email.trim(),
          passwordHash,
          name: row.name.trim(),
          role: assignedRole,
          emailVerified: true,       // usable immediately with the generated password
          onboardingComplete: false,
          jobRole:        row.jobRole || '',
          department:     row.department || '',
          jobDescription: row.jobDescription || '',
          companyName:    row.companyName || req.user.companyName || '',
          companyId,
          employeeId:     row.employeeId || '',
          phone:          row.phone || '',
          status:         row.status && ['active','inactive','blocked'].includes(row.status) ? row.status : 'active',
        });

        existingEmails.add(row.email.toLowerCase());

        created.push({
          userId:       user.userId,
          name:         user.name,
          email:        user.email,
          tempPassword,                // plaintext — included in Excel, never stored
          managerEmail: row.managerEmail || '',
          _userObj:     user,
          _emailPayload: {
            name:        user.name,
            role:        assignedRole,
            companyName: user.companyName || req.user.companyName || 'SkillForge AI',
            fromEmail:   req.user.email,
          },
        });
      } catch (e) {
        failed.push({ row, reason: e.message });
      }
    }

    // Build credential Excel (xlsx) — base64 so frontend can trigger download
    let credentialExcelB64 = null;
    if (created.length > 0) {
      try {
        const XLSX = await import('xlsx');
        const wsData = [
          ['Employee Name', 'Employee Email', 'Generated Password'],
          ...created.map(u => [u.name, u.email, u.tempPassword]),
        ];
        const wb = XLSX.utils.book_new();
        const ws = XLSX.utils.aoa_to_sheet(wsData);
        ws['!cols'] = [{ wch: 30 }, { wch: 35 }, { wch: 20 }];
        XLSX.utils.book_append_sheet(wb, ws, 'Credentials');
        const buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
        credentialExcelB64 = buf.toString('base64');
      } catch (xlsxErr) {
        console.warn('[bulk-import] Excel generation failed:', xlsxErr.message);
      }
    }

    // ── Manager linking pass ──────────────────────────────────────────────────
    // Re-fetch all users so newly created ones are visible
    const managerLinked = [], managerFailed = [];
    const needsManager = created.filter(u => u.managerEmail);
    if (needsManager.length > 0) {
      const freshUsers = await UserStore.getAllUsers({});
      const byEmail = Object.fromEntries(freshUsers.map(u => [u.email?.toLowerCase(), u]));

      for (const emp of needsManager) {
        const managerEmail = emp.managerEmail.toLowerCase();
        const manager = byEmail[managerEmail];
        if (!manager || !['manager', 'admin'].includes(manager.role)) {
          managerFailed.push({ email: emp.email, reason: `Manager "${emp.managerEmail}" not found or not a manager role` });
          continue;
        }
        try {
          await UserStore.updateUser(emp.userId, { managerId: manager.userId });
          await UserStore.assignEmployeesToManager(manager.userId, [emp.userId], req.user.userId).catch(() => {});
          managerLinked.push({ email: emp.email, manager: manager.email });
        } catch (e) {
          managerFailed.push({ email: emp.email, reason: e.message });
        }
      }
    }

    // ── Send invitation emails + auto-assign assessments (fire-and-forget) ──────
    const emailResults = {};
    setImmediate(async () => {
      for (const u of created) {
        // Email
        if (u._emailPayload) {
          try {
            const result = await Promise.race([
              EmailService.sendInvitationEmail(u.email, u._emailPayload),
              new Promise(resolve => setTimeout(() => resolve({ success: false, error: 'timeout' }), 25000)),
            ]);
            emailResults[u.email] = result?.success ? 'sent' : (result?.error || 'failed');
            if (!result?.success) console.warn(`[bulk-import] Email to ${u.email}: ${result?.error}`);
          } catch (e) {
            emailResults[u.email] = e.message;
            console.warn(`[bulk-import] Email to ${u.email} failed:`, e.message);
          }
        }
        // Auto pre-assessment
        if (u._userObj?.jobRole) {
          await autoAssignPreAssessment(u._userObj).catch(e =>
            console.error(`[bulk-import] Auto-assessment failed for ${u.email}:`, e.message)
          );
        }
      }
      console.log('[bulk-import] Email results:', emailResults);
    });

    res.status(201).json({
      success: true,
      data: {
        created: created.length,
        updated: updated.length,
        skipped: skipped.length,
        failed:  failed.length,
        managerLinked: managerLinked.length,
        credentialExcel: credentialExcelB64,   // base64 xlsx — frontend triggers download
        results: {
          created: created.map(({ managerEmail: _m, _emailPayload: _ep, _userObj: _u, ...u }) => u),
          updated,
          skipped,
          failed,
          managerLinked,
          managerFailed,
        },
      },
    });
  } catch (e) {
    console.error('[bulk-import]', e);
    res.status(500).json({ success: false, error: e.message });
  }
});

/**
 * POST /api/users/bulk-manager-mapping
 * CSV/JSON array of { employeeEmail, managerEmail } — updates managerId and group membership.
 */
router.post('/bulk-manager-mapping', authenticate, requireRole('admin'), async (req, res) => {
  try {
    const { rows } = req.body;
    if (!Array.isArray(rows) || !rows.length) {
      return res.status(400).json({ success: false, error: 'rows array required. Each row: { employeeEmail, managerEmail }' });
    }
    const allUsers = await UserStore.getAllUsers({});
    const byEmail = Object.fromEntries(allUsers.map(u => [u.email?.toLowerCase(), u]));
    const allGroups = await Groups.getAll();
    const companyId = req.user.companyId || 'default';

    const mapped = [], skipped = [], errors = [];

    for (const row of rows) {
      const empEmail = (row.employeeEmail || row.employee_email || '').toLowerCase().trim();
      const mgrEmail = (row.managerEmail || row.manager_email || '').toLowerCase().trim();
      if (!empEmail || !mgrEmail) { skipped.push({ row, reason: 'Missing email' }); continue; }

      const employee = byEmail[empEmail];
      const manager  = byEmail[mgrEmail];
      if (!employee) { errors.push({ row, reason: `Employee "${empEmail}" not found` }); continue; }
      if (!manager)  { errors.push({ row, reason: `Manager "${mgrEmail}" not found` }); continue; }
      if (!['manager','admin'].includes(manager.role)) { errors.push({ row, reason: `"${mgrEmail}" is not a manager/admin role` }); continue; }

      try {
        await UserStore.updateUser(employee.userId, { managerId: manager.userId });

        // Add employee to manager's group
        let managerGroup = allGroups.find(g =>
          g.managerId === manager.userId &&
          (g.companyId || 'default') === (manager.companyId || 'default')
        );
        if (managerGroup) {
          const ids = new Set(managerGroup.employeeIds || []);
          ids.add(employee.userId);
          await Groups.update(managerGroup.id, { employeeIds: [...ids] });
          managerGroup.employeeIds = [...ids];
        } else {
          const newGroup = {
            id: `group_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,
            name: `${manager.name || mgrEmail} Team`,
            managerId: manager.userId,
            employeeIds: [employee.userId],
            companyId: manager.companyId || companyId,
            createdBy: req.user.userId,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            status: 'active',
          };
          await Groups.create(newGroup);
          allGroups.push(newGroup);
        }
        mapped.push({ employee: empEmail, manager: mgrEmail });
      } catch (e) {
        errors.push({ row, reason: e.message });
      }
    }

    res.json({ success: true, data: { mapped: mapped.length, skipped: skipped.length, errors: errors.length, results: { mapped, skipped, errors } } });
  } catch (e) {
    console.error('[bulk-manager-mapping]', e);
    res.status(500).json({ success: false, error: e.message });
  }
});

/**
 * POST /api/users/bulk-update
 * CSV/JSON array of { email, jobRole?, department?, managerEmail?, group?, accessRights? }
 */
router.post('/bulk-update', authenticate, requireRole('admin'), async (req, res) => {
  try {
    const { rows } = req.body;
    if (!Array.isArray(rows) || !rows.length) {
      return res.status(400).json({ success: false, error: 'rows array required' });
    }
    const allUsers = await UserStore.getAllUsers({});
    const byEmail  = Object.fromEntries(allUsers.map(u => [u.email?.toLowerCase(), u]));
    const allGroups = await Groups.getAll();
    const companyId = req.user.companyId || 'default';
    const VALID_ACCESSES = ['admin', 'manager', 'trainer'];

    const updated = [], skipped = [], errors = [];

    for (const row of rows) {
      const email = (row.email || '').toLowerCase().trim();
      if (!email) { skipped.push({ row, reason: 'No email' }); continue; }

      const user = byEmail[email];
      if (!user) { errors.push({ row, reason: `User "${email}" not found` }); continue; }

      try {
        const patch = {};
        if (row.jobRole || row.job_role)     patch.jobRole    = (row.jobRole || row.job_role).trim();
        if (row.department)                   patch.department = row.department.trim();
        if (row.accessRights || row.access_rights) {
          const incoming = (row.accessRights || row.access_rights).split(/[,;|\s]+/).map(s => s.trim().toLowerCase()).filter(s => VALID_ACCESSES.includes(s));
          if (incoming.length) patch.accesses = incoming;
        }

        if (row.managerEmail || row.manager_email) {
          const mgrEmail = (row.managerEmail || row.manager_email).toLowerCase().trim();
          const mgr = byEmail[mgrEmail];
          if (mgr && ['manager','admin'].includes(mgr.role)) patch.managerId = mgr.userId;
        }

        if (Object.keys(patch).length) await UserStore.updateUser(user.userId, patch);

        // Group assignment
        if (row.group) {
          const groupName = row.group.trim();
          let grp = allGroups.find(g =>
            (g.name || '').toLowerCase() === groupName.toLowerCase() &&
            (g.companyId || 'default') === (user.companyId || 'default')
          );
          if (grp) {
            const ids = new Set(grp.employeeIds || []);
            ids.add(user.userId);
            await Groups.update(grp.id, { employeeIds: [...ids] });
            grp.employeeIds = [...ids];
          }
        }

        updated.push({ email });
        byEmail[email] = { ...user, ...patch };
      } catch (e) {
        errors.push({ row, reason: e.message });
      }
    }

    res.json({ success: true, data: { updated: updated.length, skipped: skipped.length, errors: errors.length, results: { updated, skipped, errors } } });
  } catch (e) {
    console.error('[bulk-update]', e);
    res.status(500).json({ success: false, error: e.message });
  }
});

/**
 * GET /api/users/:userId/skills-gap
 * Compare role's required skills vs employee's demonstrated skills
 */
router.get('/:userId/skills-gap', authenticate, async (req, res) => {
  try {
    const user = await UserStore.getUserById(req.params.userId);
    if (!user) return res.status(404).json({ success: false, error: 'User not found' });
    const { RoleLibrary } = await import('../services/DataStore.js');
    const role = user.jobRole ? await RoleLibrary.findByName(user.jobRole, user.companyId || 'default') : null;
    const required    = role?.skills || [];
    const demonstrated = user.jdSkills || [];
    const missing = required.filter(s => !demonstrated.some(d => d.toLowerCase() === s.toLowerCase()));
    const matched = required.filter(s =>  demonstrated.some(d => d.toLowerCase() === s.toLowerCase()));
    const coverage = required.length ? Math.round((matched.length / required.length) * 100) : null;
    res.json({ success: true, data: {
      roleName: user.jobRole || null,
      roleFound: !!role,
      required, demonstrated, missing, matched,
      coverage, // null if role has no skills defined
    }});
  } catch (e) {
    res.status(500).json({ success: false, error: e.message });
  }
});

/**
 * GET /api/users/:userId/checklist
 * Get onboarding checklist for employee
 */
router.get('/:userId/checklist', authenticate, async (req, res) => {
  try {
    const { EmployeeChecklists } = await import('../services/DataStore.js');
    const checklist = await EmployeeChecklists.getByUserId(req.params.userId);
    res.json({ success: true, data: checklist });
  } catch (e) {
    res.status(500).json({ success: false, error: e.message });
  }
});

export default router;
